### PR TITLE
Added sdklib and updated sdkapi

### PR DESCRIPTION
**Pull request by williamexperian**

### CODE REVIEW

**Comment by williamexperian** [comment]
> Please update the `README.md` in `2.0.0-preview` branch to mention `sdklib` too, especially in the `gradle` and maven section.
> 
> Also try to setup a simple custom step project that depends on both sdkapi and sdklib to ensure that gradle can download the dependencies.

@yudhistira-arya 

Thank you Yudhi, I have made the changes in the 2.0.0-preview-example-steps branch :) 

[https://github.com/experiandataquality/aperture-data-studio-sdk/tree/2.0.0-preview-example-steps](url)

**Comment by yudhistira-arya** [comment]
Could you update the `README.md` in `2.0.0-Preview` branch too?

**Comment by yudhistira-arya** [comment]
Also the link above return with 404 Page Not Found.

**Comment by williamexperian** [comment]
@yudhistira-arya 

Sorry about the broken link, should be fixed now :) 

I plan to merge this branch into `2.0.0-Preview` (it has the updated README.md) :)
https://github.com/experiandataquality/aperture-data-studio-sdk/tree/2.0.0-preview-example-steps

**Pull request merged**
